spring:
  datasource:
    url: jdbc:mysql://db:3306/calculator_db
    username: calculator_user
    password: secureUserPassword456
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect

server:
  port: 5000

jwt:
  secret: SHDFAKSHDAOIW9438934JDHHSKDFJHIEW
