version: '3.8'

services:
  db:
    image: mariadb:latest
    container_name: calculator_db
    environment:
      MYSQL_ROOT_PASSWORD: secureRootPassword123
      MYSQL_DATABASE: calculator_db
      MYSQL_USER: calculator_user
      MYSQL_PASSWORD: secureUserPassword456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
